const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
const AUTH_POST_LOGOUT_REDIRECT_URL = import.meta.env
  .VITE_AUTH_POST_LOGOUT_REDIRECT_URI;
export { API_BASE_URL, AUTH_POST_LOGOUT_REDIRECT_URL };
